### ISSUE TITLE
dedicated URL to get all parties

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-backend#13]
We'll need an url to get all parties too.

_Originally posted by @jnnkB in https://github.com/Jugendhackt/parteiduell-backend/issues/12#issuecomment-537166368_

**Comment by gruselhaus** [comment]
Einfach nur alle möglichen Parteien?

**Comment by jnnkB** [comment]
Ja

**Comment by redsolver** [comment]
Alle Parteien, oder nur die, welche zur Auswahl bei der Quizfrage zur Verfügung stehen (also die bekannten)?

**Comment by jnnkB** [comment]
Die Idee war, dass meine an einer URL alle Parteien bekommt, die von denen man Statements bekommen kann. Das wäre halt hilfreich, wenn man ein Interface zum Auswählen der relevanten Parteien baut.
