### ISSUE TITLE
Parteien tauchen mehrfach auf

### ISSUE THREAD

**Issue by jnnkB** [Jugendhackt/parteiduell-backend#15]
```CSU
CDU
CDU/CSU

GRÜNE
GRPNE/B 90
Bündnis 90/Die Grünen
Die Grünen

PIRATEN
PIRATEN //Mit Space

Die PARTEI
Die PARTEI //Mit Space
DIE PARTEI

DIE LINKE
Die LINKE
DIE LINKE.
```

**Comment by redsolver** [comment]
Ich nehme Mal an, das passiert bei den neuen Daten (Landtagswahlen etc.)?

**Comment by jnnkB** [comment]
Das kommt von /allParties

**Comment by redsolver** [comment]
Ok, also von allen Datenquellen. Ich schau mir das heute noch später Mal an, hab jetzt gerade leider keine Zeit.

**Comment by redsolver** [comment]
Hab aber schon eine Lösung

**Comment by redsolver** [comment]
@jnnkB Sollen "CDU" und "CSU" als einzelne Parteien oder als "CDU/CSU" gehandhabt werden?

**Comment by jnnkB** [comment]
Ich denke das sollten alle entscheiden und nicht nur wir. Daher könnten wir durch Daumen hoch/runter abstimmen.

@Max20013108 @lmaertens @gruselhaus 
👍 : CDU/CSU
👎 : CDU und CSU

**Comment by redsolver** [comment]
Wichtig: Auch wenn CDU und CSU zusätzlich einzeln betrachtet werde, gibt es natürlich trotzdem noch "CDU/CSU" für Europawahl etc.

**Comment by redsolver** [comment]
Wenn weitere Parteien doppelt vorkommen, einfach neues Issue aufmachen. Hab jetzt nix mehr entdeckt.
