### ISSUE TITLE
GET-Parameter on /allParties specifing the datasource

### ISSUE THREAD

**Issue by jnnkB** [Jugendhackt/parteiduell-backend#16]
Then we could show the parties for the selected datasources

**Comment by redsolver** [comment]
@jnnkB Ist jetzt drin

**Comment by redsolver** [comment]
@gruselhaus Wozu ist eigentlich das `done` label? Wenn das Issue zu ist, ist es fertig - wozu noch ein label?

**Comment by jnnkB** [comment]
Could you make it able to take multiple sources

**Comment by redsolver** [comment]
Ok - ab gehts

**Comment by gruselhaus** [comment]
> @gruselhaus Wozu ist eigentlich das `done` label? Wenn das Issue zu ist, ist es fertig - wozu noch ein label?

Manchmal wird ein Issue ja abgewiesen - so hat mein in der Übersicht die Möglichkeit diese schnell rauszufiltern.

**Comment by jnnkB** [comment]
> @gruselhaus Wozu ist eigentlich das `done` label? Wenn das Issue zu ist, ist es fertig - wozu noch ein label?

Ich glaube weil auch Issues geschlossenwerden können, wenn das Problem nicht behoben ist, beispielsweise, wenn man es lösen kann

**Comment by redsolver** [comment]
> Could make it able to take multiple sources

Closed in https://github.com/Jugendhackt/parteiduell-backend/commit/86110c82b666d0bb192815122afc025125d80699

**Comment by jnnkB** [comment]
Could you rename it to sources? Would make the API more consistent.
