### ISSUE TITLE
Deploy auf Ubuntu Server

### ISSUE THREAD

**Issue by gruselhaus** [Jugendhackt/parteiduell-backend#22]
@redsolver ich will das Backend mit auf den Managed Server draufpacken, auf dem aktuell auch das Frontend läuft. Kann man das Dart Programm als Task laufen lassen?

**Comment by redsolver** [comment]
Was genau meinst du mit Task? Dart kann man von Docker bis screen laufen lassen wie man will.

**Comment by gruselhaus** [comment]
Was meinst du mit "bis screen"?

**Comment by redsolver** [comment]
https://www.bergercity.de/linux/screen-tastenkurzel/

**Comment by redsolver** [comment]
Nur ein Beispiel, kann man nutzen um schnell Programme halbwegs verwaltet im Hintergrund zu starten

**Comment by redsolver** [comment]
Aber was meinst du jetzt mit Task?

**Comment by gruselhaus** [comment]
https://thosakwe.com/deploying-dart-apps-to-linux/#step-6-running-your-dart-code-as-a-daemon

**Comment by niccokunzmann** [comment]
@gruselhaus, Ich habe Travis für alle Repos in JugendHackt freigeschaltet. Wenn es nicht geht, bitte Bescheid geben.

**Comment by gruselhaus** [comment]
@niccokunzmann Danke Dir!
