### ISSUE TITLE
Could you give each statement an own id and make it possible to request a specific statement using GET Parameters

### ISSUE THREAD

**Issue by jnnkB** [Jugendhackt/parteiduell-backend#27]
This would be needed for https://github.com/Jugendhackt/parteiduell-frontend/issues/18

**Comment by redsolver** [comment]
Soll die ID ein Hash aus der These sein oder sollen die IDs einfach durchgezählt werden?

**Comment by jnnkB** [comment]
Also ich hätte hoch gezählt aber eigentlich ist es relativ egal

**Comment by jnnkB** [comment]
Gibt es nicht auch welche im Datensatz? Das würde doch am meisten Sinn machen.

**Comment by redsolver** [comment]
Stimmt, dann verwende ich die.

**Comment by gruselhaus** [comment]
<img width="349" alt="Bildschirmfoto 2019-10-14 um 18 05 56" src="https://user-images.githubusercontent.com/33380107/66766043-78813f80-eead-11e9-918d-22ff6934e83f.png">

**Comment by redsolver** [comment]
Feature fertig implementiert mit https://github.com/Jugendhackt/parteiduell-backend/commit/edad95580597229ff36982372c4725c5ce04b1fa

**Comment by gruselhaus** [comment]
In den Stammdaten scheint nicht immer eine Id vorhanden zu sein.
