### ISSUE TITLE
mit missing data umgehen

### ISSUE THREAD

**Issue by livgm** [Jugendhackt/parteiduell-backend#4]
Was machen wir mit missing data? kann das noch als parameter übergeben werden? oder komplett herausgefiltert werden?

**Comment by jnnkB** [comment]
Ich wäre dafür das du @redsolver Statements wie 

```html
Zu dieser These hat die Partei <span class='text-bold bg-yellow-light rounded-1 d-inline-block'>keine</span> <span class='text-bold bg-yellow-light rounded-1 d-inline-block'>Begründung</span>
```

einfach heraus filterst.

**Comment by redsolver** [comment]
> Ich wäre dafür das du @redsolver Statements wie
> 
> ```
> Zu dieser These hat die Partei <span class='text-bold bg-yellow-light rounded-1 d-inline-block'>keine</span> <span class='text-bold bg-yellow-light rounded-1 d-inline-block'>Begründung</span>
> ```
> 
> einfach heraus filterst.

Warum ist da HTML drin? Der Server gibt nur "Diese Partei hat keine Erklärung zu dieser These abgegeben." zurück.

**Comment by jnnkB** [comment]
Das hab ich über die github Suche am Handy in deinem Repository gefunden.

**Comment by redsolver** [comment]
Ok, dann sollen Statements ohne Inhalt einfach nicht in die Auswahl genommen werden? Dann könnte es aber passieren, dass nur 2 Antwortmöglichkeiten übrig bleiben.

**Comment by jnnkB** [comment]
Sollte eigentlich kein Problem sein. wenn es halt nur noch eine ist wäre das blöd.
